### PR TITLE
fix: add file extension at the end of filename if not provided

### LINKED ISSUE #14: if custom filename don't have extension it should return error or automaticaly fix
as an example [this code](https://github.com/go-shiori/go-epub/pull/13#issuecomment-1774926463) use custom name `SubSectionName` it generate `SubSectionName` file without extension(xhtml) that can create error in some of ebook reader.
to avoid that `go-epub` should add extension automatically or return error.

### PR DESCRIPTION
**Pull request by Monirzadeh**
this pull request try to fix #14 and add some more unit test for `addSection` function

### CODE REVIEW

File: epub_test.go [hunk 1]
```diff
@@ -517,6 +517,16 @@ func TestAddSubSection(t *testing.T) {
 	if err != nil {
 		t.Errorf("Error adding subsection: %s", err)
 	}
+	// append subsection to a subsection
+	testSubSection2Path, err := e.AddSubSection(testSection2Path, testSectionBody, testSectionTitle, "", "")
+	if err != nil {
+		t.Errorf("Error adding subsection: %s", err)
+	}
+	// append subsection to a parrent that not exist
```
Comment (fmartingr) [inline epub_test.go:525]:
```suggestion
	// Append subsection to a parent that not exist
```

File: epub_test.go [hunk 2]
```diff
@@ -841,6 +868,22 @@ func TestSetCover(t *testing.T) {
 	cleanup(testEpubFilename, tempDir)
 }
 
+func TestSectionAppender(t *testing.T) {
```
Comment (fmartingr) [inline epub_test.go:871]: Is this finished or is an example?

File: epub_test.go [hunk 3]
```diff
@@ -1342,3 +1385,43 @@ func writeAndExtractEpub(t testing.TB, e *Epub, epubFilename string) string {
 
 	return tempDir
 }
+
+func TestAddSubSection_with_custome_filename(t *testing.T) {
```
Comment (fmartingr) [inline epub_test.go:1389]:
```suggestion
func TestAddSubSectionWithCustomFilename(t *testing.T) {
```

**Review by fmartingr — CHANGES_REQUESTED** [review]
Just some text typos and a question

File: epub_test.go (hunk 2 above)
Comment (fmartingr) [reply epub_test.go]: Maybe we should remove the comments inside the structures then? It's confusing having a comment to define something but the test is checking the not found, that's why I though it was an example.

**Review by fmartingr — APPROVED** [review]

File: epub.go [hunk 4]
```diff
@@ -355,7 +352,12 @@ func (e *Epub) addSection(parentFilename string, body string, sectionTitle strin
 			}
 		}
 	} else {
-		// if internalFilename is not empty check that is not duplicate
+		// if internalFilename is not empty, check that it has .xhtml at the end.
+		// if it doesn't have add .xhtml at the end
+		// than if it is duplicate return error
+		if !strings.HasSuffix(internalFilename, ".xhtml") {
```
Comment (fmartingr) [inline epub.go:358]: Should an error be raised if the user tries to add a filename which has an extension but it's not `.xhtml`?

Maybe is better to check the actual extension with [`filepath.Ext`](https://pkg.go.dev/path/filepath#Ext) ?

Comment (fmartingr) [reply epub.go]: Ooww, I understand now. Then if every content file should be `xhtml` maybe you don't need to do all things like that. Because a binary file can't be embedded as a section, right? It should be added to the ebook but displayed in a `xhtml` file.

Comment (fmartingr) [reply epub.go]: It that's the case I don't think so. 👍

**Review by fmartingr — APPROVED** [review]
